
package javaapplication12;

import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.net.Socket;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.net.URL;
import java.io.File;

/**
 *
 * @author ASUS
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private Timer imageTimer; // Timer for hiding image
    private Timer answerTimer; // Timer for answer submission
    private int imageTimeLeft = 15; // 15 seconds for image viewing
    private int answerTimeLeft = 15; // 15 seconds for answering
    private JPanel questionPanel;
    private JRadioButton option1, option2, option3;
    private ButtonGroup optionsGroup;
    private JLabel questionLabel;
    private JLabel timerLabel;
    private ScorePanel scorePanel;
    private static final String CORRECT_ANSWER = "1";
    private Socket socket;
    private PrintWriter out;
    private BufferedReader in;
    private boolean answerSubmitted = false;
    private int playerScore = 0;

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1(Socket socket, PrintWriter out, BufferedReader in) {
        this.socket = socket;
        this.out = out;
        this.in = in;
        
        // Initialize timer label
        timerLabel = new JLabel("Time left: " + imageTimeLeft + "s");
        timerLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        timerLabel.setHorizontalAlignment(SwingConstants.CENTER);
        
        // Initialize score panel
        scorePanel = new ScorePanel();
        
        initComponents();
        startImageTimer();
        hideQuestionAndOptions();
        startMessageListener();
        
        // Request initial scores
        out.println("GET_SCORES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPanel.setBackground(new Color(255, 240, 245)); // Light pink background

        // Create header panel
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));
        headerPanel.setBackground(new Color(255, 182, 193)); // Pink
        
        jLabel2 = new javax.swing.JLabel("Focus on all the elements in the picture");
        jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 24));
        jLabel2.setForeground(new Color(139, 69, 19)); // Brown text
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        headerPanel.add(jLabel2, BorderLayout.CENTER);
        
        // Add timer to the left
        timerLabel.setForeground(new Color(139, 69, 19)); // Brown text
        headerPanel.add(timerLabel, BorderLayout.WEST);
        
        // Add score panel to the right
        headerPanel.add(scorePanel, BorderLayout.EAST);
        
        // Create image panel
        JPanel imagePanel = new JPanel(new BorderLayout());
        imagePanel.setBorder(BorderFactory.createLineBorder(new Color(255, 140, 0), 2)); // Orange border
        imagePanel.setBackground(new Color(255, 240, 245)); // Light pink background
        jLabel1 = new javax.swing.JLabel();
        try {
            ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/images/HOWMANY.png"));
            if (icon.getImage() == null) {
                jLabel1.setText("Image not available");
                jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 24));
            } else {
                Image img = icon.getImage();
                Image scaledImg = img.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
                jLabel1.setIcon(new ImageIcon(scaledImg));
            }
        } catch (Exception e) {
            jLabel1.setText("Error loading image");
            jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 24));
        }
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        imagePanel.add(jLabel1, BorderLayout.CENTER);
        
        // Create question panel
        questionPanel = new JPanel();
        questionPanel.setLayout(new BoxLayout(questionPanel, BoxLayout.Y_AXIS));
        questionPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        questionPanel.setBackground(new Color(255, 228, 225)); // Misty rose background
        
        jLabel3 = new javax.swing.JLabel("How many fruits were on the picture?");
        jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 18));
        jLabel3.setForeground(new Color(139, 69, 19)); // Brown text
        jLabel3.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        // Create radio buttons
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton("8 fruits");
        jRadioButton2 = new javax.swing.JRadioButton("6 fruits");
        jRadioButton3 = new javax.swing.JRadioButton("10 fruits");
        
        // Style radio buttons
        Font optionFont = new Font("Segoe UI", Font.PLAIN, 16);
        Color radioBtnColor = new Color(255, 140, 0); // Orange
        
        for (JRadioButton btn : new JRadioButton[]{jRadioButton1, jRadioButton2, jRadioButton3}) {
            btn.setFont(optionFont);
            btn.setForeground(new Color(139, 69, 19)); // Brown text
            btn.setBackground(new Color(255, 228, 225)); // Misty rose background
            btn.setAlignmentX(Component.CENTER_ALIGNMENT);
            buttonGroup1.add(btn);
        }
        
        // Create submit button
        jButton1 = new javax.swing.JButton("Submit Answer");
        jButton1.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jButton1.setBackground(new Color(255, 140, 0)); // Orange
        jButton1.setForeground(Color.WHITE);
        jButton1.setFocusPainted(false);
        jButton1.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jButton1.setAlignmentX(Component.CENTER_ALIGNMENT);
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        
        // Add components to question panel
        questionPanel.add(jLabel3);
        questionPanel.add(Box.createVerticalStrut(20));
        questionPanel.add(jRadioButton1);
        questionPanel.add(Box.createVerticalStrut(10));
        questionPanel.add(jRadioButton2);
        questionPanel.add(Box.createVerticalStrut(10));
        questionPanel.add(jRadioButton3);
        questionPanel.add(Box.createVerticalStrut(30));
        questionPanel.add(jButton1);
        
        // Add all panels to main panel
        mainPanel.add(headerPanel, BorderLayout.NORTH);
        mainPanel.add(imagePanel, BorderLayout.CENTER);
        mainPanel.add(questionPanel, BorderLayout.SOUTH);
        
        // Set frame properties
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Game - Round 1");
        setPreferredSize(new Dimension(800, 800));
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(mainPanel, BorderLayout.CENTER);
        getContentPane().setBackground(new Color(255, 240, 245)); // Light pink background
        pack();
        setLocationRelativeTo(null);
        
        setupUI();
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        // Apply theme to frame
        QuizTheme.styleFrame(this);
        
        // Style the buttons
        QuizTheme.styleButton(jButton1);
        
        // Style radio buttons
        QuizTheme.styleRadioButton(jRadioButton1);
        QuizTheme.styleRadioButton(jRadioButton2);
        QuizTheme.styleRadioButton(jRadioButton3);
        
        // Style panels
        for (Component comp : getContentPane().getComponents()) {
            if (comp instanceof JPanel) {
                QuizTheme.stylePanel((JPanel)comp);
            }
        }
        
        // Style labels
        for (Component comp : getContentPane().getComponents()) {
            if (comp instanceof JLabel) {
                if (((JLabel)comp).getFont().getSize() > 16) {
                    QuizTheme.styleTitleLabel((JLabel)comp);
                } else {
                    QuizTheme.styleLabel((JLabel)comp);
                }
            }
        }
        
        // Load the image
        try {
            String imagePath = "/Users/mohammedalgumlas/Downloads/JavaApplication12 2/src/images/HOWMANY.png";
            File imageFile = new File(imagePath);
            if (imageFile.exists()) {
                ImageIcon icon = new ImageIcon(imagePath);
                Image img = icon.getImage();
                Image newImg = img.getScaledInstance(400, 300, Image.SCALE_SMOOTH);
                jLabel1.setIcon(new ImageIcon(newImg));
            } else {
                System.err.println("Image not found at: " + imagePath);
                jLabel1.setText("Image not found");
            }
        } catch (Exception e) {
            System.err.println("Error loading image: " + e.getMessage());
            jLabel1.setText("Error loading image");
            e.printStackTrace();
        }
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        checkAnswer();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    ;

    /**
     * Start the timer that will hide the image after 15 seconds.
     */
    private void startImageTimer() {
        imageTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                imageTimeLeft--;
                timerLabel.setText("Time left: " + imageTimeLeft + "s");
                System.out.println("Image time left: " + imageTimeLeft); // Debug print
                
                if (imageTimeLeft <= 0) {
                    imageTimer.stop();
                    jLabel1.setVisible(false);
                    jLabel2.setText("Choose the correct option:");
                    showQuestionAndOptions();
                    startAnswerTimer();
                }
            }
        });
        imageTimer.start();
    }

    private void startAnswerTimer() {
        answerTimeLeft = 15; // Reset to 15 seconds
        System.out.println("Starting answer timer: " + answerTimeLeft + " seconds"); // Debug print
        
        answerTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                answerTimeLeft--;
                timerLabel.setText("Time to answer: " + answerTimeLeft);
                System.out.println("Answer time left: " + answerTimeLeft); // Debug print
                
                if (answerTimeLeft <= 0) {
                    System.out.println("Timer finished, moving to next frame"); // Debug print
                    answerTimer.stop();
                    
                    // If no answer was submitted, send a default answer
                    if (!answerSubmitted) {
                        System.out.println("No answer submitted, sending default"); // Debug print
                        out.println("ANSWER:0");
                    }
                    
                    // Create and show next frame
                    SwingUtilities.invokeLater(() -> {
                        try {
                            System.out.println("Creating NewJFrame2"); // Debug print
                            NewJFrame2 nextFrame = new NewJFrame2(socket, out, in);
                            nextFrame.setVisible(true);
                            System.out.println("NewJFrame2 created and visible"); // Debug print
                            dispose();
                            System.out.println("NewJFrame1 disposed"); // Debug print
                        } catch (Exception ex) {
                            System.err.println("Error creating next frame: " + ex.getMessage());
                            ex.printStackTrace();
                        }
                    });
                }
            }
        });
        answerTimer.start();
    }

    // Hide the question and radio buttons initially.
    private void hideQuestionAndOptions() {
        jLabel3.setVisible(false); // Hide the question label
        jRadioButton1.setVisible(false); // Hide radio button 1
        jRadioButton2.setVisible(false); // Hide radio button 2
        jRadioButton3.setVisible(false); // Hide radio button 3
        jButton1.setVisible(false); // Hide submit button initially
    }

    // Show the question and radio buttons after the image has been hidden
    private void showQuestionAndOptions() {
        jLabel3.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jRadioButton3.setVisible(true);
        jButton1.setVisible(true);
    }

    // Check the selected answer
    private void checkAnswer() {
        if (!answerSubmitted) {
            String selectedOption = getSelectedAnswer();
            out.println("ANSWER:" + selectedOption);
            
            // Update score if correct answer is selected
            if (selectedOption.equals(CORRECT_ANSWER)) {
                playerScore += 10;
                out.println("SCORE:" + playerScore);
            }
            
            answerSubmitted = true;
            jButton1.setEnabled(false);
        }
    }

    private String getSelectedAnswer() {
        if (jRadioButton1.isSelected()) {
            return "1";
        } else if (jRadioButton2.isSelected()) {
            return "2";
        } else if (jRadioButton3.isSelected()) {
            return "3";
        }
        return "";
    }

    private void startMessageListener() {
        new Thread(() -> {
            try {
                String message;
                while ((message = in.readLine()) != null) {
                    if (message.startsWith("SCORES:")) {
                        final String scoreData = message;
                        SwingUtilities.invokeLater(() -> {
                            scorePanel.updateScores(scoreData);
                        });
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
